spring.application.name=gestion-conges-back
server:
    error:
      include-message:always
      include-binding-errors:always

server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/conges
spring.datasource.username=postgres
spring.datasource.password=2003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG


app.seed.rh.email=rh@gestion-conges.com
app.seed.rh.password=ChangezMoi123!
app.seed.rh.nom=Admin
app.seed.rh.prenom=RH